# Generated by Django 5.2.3 on 2025-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahityo_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
