# Generated by Django 5.2.3 on 2025-07-12 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahityo_core", "0003_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcompetition",
            name="sector",
            field=models.ForeignKey(
                default=uuid.UUID("66015e2f-b91d-47e3-8d94-e791927d6eca"),
                on_delete=django.db.models.deletion.CASCADE,
                to="sahityo_core.sector",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="sector",
            field=models.ForeignKey(
                default=uuid.UUID("66015e2f-b91d-47e3-8d94-e791927d6eca"),
                on_delete=django.db.models.deletion.CASCADE,
                to="sahityo_core.sector",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="sector",
            field=models.ForeignKey(
                default=uuid.UUID("66015e2f-b91d-47e3-8d94-e791927d6eca"),
                on_delete=django.db.models.deletion.CASCADE,
                to="sahityo_core.sector",
            ),
        ),
    ]
