# Generated by Django 5.2.3 on 2025-07-12 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahityo_core", "0004_scheduledcompetition_sector_stage_sector_unit_sector"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduledcompetition",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="scheduledcompetition",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduled_competitions",
                to="sahityo_core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="stage",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="sahityo_core.sector",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="sahityo_core.sector",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduledcompetition",
            unique_together={("competition", "sector")},
        ),
        migrations.CreateModel(
            name="ParticipantPresent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_1_present", models.BooleanField(default=False)),
                ("participant_2_present", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="sahityo_core.scheduledcompetition",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sahityo_core.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant Present",
                "verbose_name_plural": "Participants Present",
                "unique_together": {("scheduled_competition", "unit")},
            },
        ),
    ]
