from django.db import migrations
import uuid

def load_initial_data(apps, schema_editor):
    Category = apps.get_model('sahityo_core', 'Category')
    Competition = apps.get_model('sahityo_core', 'Competition')

    # Define categories
    categories = [
        'Lower Primary',
        'Lower Primary (Girls)',
        'Upper Primary',
        'Upper Primary (Girls)',
        'High School',
        'High School (Girls)',
        'Higher Secondary',
        'Higher Secondary (Girls)',
        'Junior',
        'Senior',
        'General',
        'Campus',
        'Campus (Girls)',
        'Campus (Girls Parallel)',
    ]

    # Create category instances and store them in a dictionary for lookup
    category_instances = {}
    for cat_name in categories:
        category = Category.objects.create(
            id=uuid.uuid4(),
            name=cat_name
        )
        category_instances[cat_name] = category

    # Define competitions with their respective categories
    competitions = [
        {'name': 'Madhganam', 'category': 'Lower Primary'},
        {'name': 'Speech', 'category': 'Lower Primary'},
        {'name': 'Quiz', 'category': 'Lower Primary'},
        {'name': 'Story Narration', 'category': 'Lower Primary'},
        {'name': 'Drawing with Pencil', 'category': 'Lower Primary'},
        {'name': 'Watercolor Drawing', 'category': 'Lower Primary'},
        {'name': 'Language Game', 'category': 'Lower Primary'},
        {'name': 'Reading Malayalam', 'category': 'Lower Primary'},
        {'name': 'Reading Arabic-Malayalam', 'category': 'Lower Primary'},
        {'name': 'Book Test', 'category': 'Lower Primary'},
        {'name': 'Drawing with Pencil (Girls)', 'category': 'Lower Primary (Girls)'},
        {'name': 'Watercolor Drawing (Girls)', 'category': 'Lower Primary (Girls)'},
        {'name': 'Handwriting Malayalam', 'category': 'Lower Primary (Girls)'},
        {'name': 'Journal Art', 'category': 'Lower Primary (Girls)'},
        {'name': 'Mappila Song', 'category': 'Upper Primary'},
        {'name': 'Story Narration', 'category': 'Upper Primary'},
        {'name': 'Speech', 'category': 'Upper Primary'},
        {'name': 'Math Game', 'category': 'Upper Primary'},
        {'name': 'Quiz', 'category': 'Upper Primary'},
        {'name': 'Drawing with Pencil', 'category': 'Upper Primary'},
        {'name': 'Watercolor Drawing', 'category': 'Upper Primary'},
        {'name': 'Story Writing', 'category': 'Upper Primary'},
        {'name': 'Book Test', 'category': 'Upper Primary'},
        {'name': 'Spelling Bee', 'category': 'Upper Primary'},
        {'name': 'Sudoku', 'category': 'Upper Primary'},
        {'name': 'Drawing with Pencil (Girls)', 'category': 'Upper Primary (Girls)'},
        {'name': 'Watercolor Drawing (Girls)', 'category': 'Upper Primary (Girls)'},
        {'name': 'Book Test (Girls)', 'category': 'Upper Primary (Girls)'},
        {'name': 'Story Writing (Girls)', 'category': 'Upper Primary (Girls)'},
        {'name': 'Origami (Girls)', 'category': 'Upper Primary (Girls)'},
        {'name': 'Speech Malayalam', 'category': 'High School'},
        {'name': 'Speech English', 'category': 'High School'},
        {'name': 'Mappila Song', 'category': 'High School'},
        {'name': 'Madhganam', 'category': 'High School'},
        {'name': 'Arabic Poem Recitation', 'category': 'High School'},
        {'name': 'Poem Recitation Malayalam', 'category': 'High School'},
        {'name': 'Poem Recitation Urdu', 'category': 'High School'},
        {'name': 'Quiz', 'category': 'High School'},
        {'name': 'Story Writing', 'category': 'High School'},
        {'name': 'Poem Writing', 'category': 'High School'},
        {'name': 'Drawing with Pencil', 'category': 'High School'},
        {'name': 'Watercolor Drawing', 'category': 'High School'},
        {'name': 'Book Test', 'category': 'High School'},
        {'name': 'Essay Malayalam', 'category': 'High School'},
        {'name': 'News Reading', 'category': 'High School'},
        {'name': 'Footnote', 'category': 'High School'},
        {'name': 'Language Game English', 'category': 'High School'},
        {'name': 'Embroidery (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Book Test (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Drawing with Pencil (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Watercolor Drawing (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Story Writing (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Poem Writing (Girls)', 'category': 'High School (Girls)'},
        {'name': 'Urdu Poem Recitation', 'category': 'Higher Secondary'},
        {'name': 'Mappila Song', 'category': 'Higher Secondary'},
        {'name': 'Bhakti Song', 'category': 'Higher Secondary'},
        {'name': 'Speech', 'category': 'Higher Secondary'},
        {'name': 'Digital Painting', 'category': 'Higher Secondary'},
        {'name': 'Story Writing', 'category': 'Higher Secondary'},
        {'name': 'Poem Writing', 'category': 'Higher Secondary'},
        {'name': 'Essay Malayalam', 'category': 'Higher Secondary'},
        {'name': 'Essay English', 'category': 'Higher Secondary'},
        {'name': 'Quiz', 'category': 'Higher Secondary'},
        {'name': 'Drawing with Pencil', 'category': 'Higher Secondary'},
        {'name': 'Watercolor Drawing', 'category': 'Higher Secondary'},
        {'name': 'Book Test', 'category': 'Higher Secondary'},
        {'name': 'News Writing', 'category': 'Higher Secondary'},
        {'name': 'Calligraphy Arabic', 'category': 'Higher Secondary'},
        {'name': 'Reel Making (Girls)', 'category': 'Higher Secondary (Girls)'},
        {'name': 'Calligraphy Arabic (Girls)', 'category': 'Higher Secondary (Girls)'},
        {'name': 'Book Test (Girls)', 'category': 'Higher Secondary (Girls)'},
        {'name': 'Story Writing (Girls)', 'category': 'Higher Secondary (Girls)'},
        {'name': 'Poem Writing (Girls)', 'category': 'Higher Secondary (Girls)'},
        {'name': 'Literary Debate', 'category': 'Junior'},
        {'name': 'Mappila Song', 'category': 'Junior'},
        {'name': 'Speech Malayalam', 'category': 'Junior'},
        {'name': 'Speech Arabic', 'category': 'Junior'},
        {'name': 'Speech English', 'category': 'Junior'},
        {'name': 'Poem Writing', 'category': 'Junior'},
        {'name': 'Story Writing', 'category': 'Junior'},
        {'name': 'Book Test', 'category': 'Junior'},
        {'name': 'Essay Malayalam', 'category': 'Junior'},
        {'name': 'Essay Arabic', 'category': 'Junior'},
        {'name': 'Slogan Writing', 'category': 'Junior'},
        {'name': 'Madh Song Writing', 'category': 'Junior'},
        {'name': 'Quiz', 'category': 'Junior'},
        {'name': 'Translation Arabic', 'category': 'Junior'},
        {'name': 'Calligraphy Arabic', 'category': 'Junior'},
        {'name': 'Social Text', 'category': 'Junior'},
        {'name': 'Hadith Moosabaka', 'category': 'Junior'},
        {'name': 'AI Poem Writing', 'category': 'Junior'},
        {'name': 'Reel Making', 'category': 'Junior'},
        {'name': 'Political Debate', 'category': 'Senior'},
        {'name': 'Mappila Song', 'category': 'Senior'},
        {'name': 'Hamd Urdu', 'category': 'Senior'},
        {'name': 'Poem Recitation English', 'category': 'Senior'},
        {'name': 'Speech Malayalam', 'category': 'Senior'},
        {'name': 'Speech English', 'category': 'Senior'},
        {'name': 'Speech Urdu', 'category': 'Senior'},
        {'name': 'Mushaara Alfiyya', 'category': 'Senior'},
        {'name': 'Poem Writing', 'category': 'Senior'},
        {'name': 'Poem Writing English', 'category': 'Senior'},
        {'name': 'Story Writing', 'category': 'Senior'},
        {'name': 'Book Test', 'category': 'Senior'},
        {'name': 'Essay Malayalam', 'category': 'Senior'},
        {'name': 'Essay English', 'category': 'Senior'},
        {'name': 'Essay Urdu', 'category': 'Senior'},
        {'name': 'Translation English', 'category': 'Senior'},
        {'name': 'Madh Song Writing', 'category': 'Senior'},
        {'name': 'Slogan Writing', 'category': 'Senior'},
        {'name': 'Quiz', 'category': 'Senior'},
        {'name': 'Feature Writing', 'category': 'Senior'},
        {'name': 'Social Text', 'category': 'Senior'},
        {'name': 'Poster Designing', 'category': 'Senior'},
        {'name': 'E-Poster', 'category': 'Senior'},
        {'name': 'Digital Illustration', 'category': 'Senior'},
        {'name': 'Magazine Layout', 'category': 'Senior'},
        {'name': 'Digital Painting', 'category': 'Senior'},
        {'name': 'Spot Magazine (5 People)', 'category': 'General'},
        {'name': 'Daf (10 People)', 'category': 'General'},
        {'name': 'Araban (10 People)', 'category': 'General'},
        {'name': 'Group Song A (4 People)', 'category': 'General'},
        {'name': 'Group Song B (4 People)', 'category': 'General'},
        {'name': 'Maulid Recitation (4 People)', 'category': 'General'},
        {'name': 'Qasida Recitation (4 People)', 'category': 'General'},
        {'name': 'Revolutionary Song (3 People)', 'category': 'General'},
        {'name': 'Wall Writing (2 People)', 'category': 'General'},
        {'name': 'Malappattu (3 People)', 'category': 'General'},
        {'name': 'Risala Quiz (2 People)', 'category': 'General'},
        {'name': 'Qawwali (5 People)', 'category': 'General'},
        {'name': 'Revolutionary Song Writing', 'category': 'General'},
        {'name': 'Mappila Song Writing', 'category': 'General'},
        {'name': 'Social Story (District)', 'category': 'General'},
        {'name': 'Project', 'category': 'General'},
        {'name': 'Collage (3 People)', 'category': 'General'},
        {'name': 'Nasheed (4 People)', 'category': 'General'},
        {'name': 'Family Magazine (Sector)', 'category': 'General'},
        {'name': 'Mappilappattu', 'category': 'Campus'},
        {'name': 'Duff Song', 'category': 'Campus'},
        {'name': 'Speech Malayalam', 'category': 'Campus'},
        {'name': 'Speech English', 'category': 'Campus'},
        {'name': 'Elocution Malayalam', 'category': 'Campus'},
        {'name': 'Elocution English', 'category': 'Campus'},
        {'name': 'Story Writing Malayalam', 'category': 'Campus'},
        {'name': 'Poetry Writing Malayalam', 'category': 'Campus'},
        {'name': 'Poetry Writing English', 'category': 'Campus'},
        {'name': 'Painting Pencil', 'category': 'Campus'},
        {'name': 'Painting Watercolor', 'category': 'Campus'},
        {'name': 'Quiz (2 persons)', 'category': 'Campus'},
        {'name': 'Book Test', 'category': 'Campus'},
        {'name': 'IT Quiz', 'category': 'Campus'},
        {'name': 'Vlogging', 'category': 'Campus'},
        {'name': 'Topic Commentary (Team)', 'category': 'Campus'},
        {'name': 'Political Debate (2 persons)', 'category': 'Campus'},
        {'name': 'Campus Magazine', 'category': 'Campus'},
        {'name': 'District Presentation (Without Stage)', 'category': 'Campus'},
        {'name': 'Clip the Flag (Without Stage)', 'category': 'Campus'},
        {'name': 'District Debate (Malayalam)', 'category': 'Campus'},
        {'name': 'Online Quiz (Team Event)', 'category': 'Campus'},
        {'name': 'App Prototyping', 'category': 'Campus'},
        {'name': 'Ideathon', 'category': 'Campus'},
        {'name': 'Elocution Malayalam', 'category': 'Campus (Girls)'},
        {'name': 'Elocution English', 'category': 'Campus (Girls)'},
        {'name': 'Story Writing Malayalam', 'category': 'Campus (Girls)'},
        {'name': 'Story Writing English', 'category': 'Campus (Girls)'},
        {'name': 'Poetry Writing Malayalam', 'category': 'Campus (Girls)'},
        {'name': 'Poetry Writing English', 'category': 'Campus (Girls)'},
        {'name': 'Painting Pencil', 'category': 'Campus (Girls)'},
        {'name': 'Painting Watercolor', 'category': 'Campus (Girls)'},
        {'name': 'App Presentation', 'category': 'Campus (Girls)'},
        {'name': 'Ideathon', 'category': 'Campus (Girls)'},
        {'name': 'Clip the Flag', 'category': 'Campus (Girls)'},
        {'name': 'Elocution Malayalam', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Elocution English', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Story Writing Malayalam', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Story Writing English', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Poetry Writing Malayalam', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Poetry Writing English', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Painting Pencil', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Painting Watercolor', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Calligraphy Arabic', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Book Test Online (State Level)', 'category': 'Campus (Girls Parallel)'},
        {'name': 'Quiz Online (State Level)', 'category': 'Campus (Girls Parallel)'},
    ]

    # Create competition instances
    for comp in competitions:
        Competition.objects.create(
            id=uuid.uuid4(),
            name=comp['name'],
            category=category_instances[comp['category']]
        )



class Migration(migrations.Migration):

    dependencies = [
        ("sahityo_core", "0005_alter_scheduledcompetition_unique_together_and_more"),
    ]


    operations = [
        migrations.RunPython(load_initial_data),
    ]