# Generated by Django 5.2.3 on 2025-07-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sahityo_core", "0006_auto_20250713_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledcompetition",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
